"""Ut99py - Unreal Tournament 99 Python Port"""

__version__ = "0.0.3"

from . import core
from . import engine
from . import audio
from . import graphics
from . import window
from . import ucc

from .core import (
    FName, FString, FTime,
    FVector, FPlane, FRotator, FQuat, FMatrix,
    TArray, TMap,
    FGuid, FCompactIndex,
    UObject, UClass, UStruct, UFunction, UState,
    UPackage, UPackageMap,
    FArchive, FArchiveFileReader, FArchiveMemoryReader, FArchiveFileWriter,
    FOutputDevice, FOutputDeviceNull, FOutputDeviceStdout, FOutputDeviceFile,
    GNull, GLog, GError,
    FFileManager, FConfigCacheIni,
    FMalloc, FMallocAnsi,
)

from .core.linkers import (
    FObjectExport,
    FObjectImport,
    FGenerationInfo,
    FPackageFileSummary as LinkerFPackageFileSummary,
    ULinker,
    ULinkerLoad,
    ULinkerSave,
    FLazyLoader,
    load_package,
)

from .engine import (
    AActor, APawn, APlayerPawn,
    AWeapon, AInventory, AAmmo, APickup,
    ABrush, AZoneInfo, ALevelInfo,
    AProjectile, ACamera, AController, APlayerController,
    AGameInfo,
    ULevel, UGameEngine,
    FCoords, FActorLink, EPhysics,
    UURL, UNetDriver, UNetConnection,
    UChannel, UControlChannel, UActorChannel, UFileChannel,
    UPendingLevel, UNetPendingLevel, EConnectionState, EChannelType,
    AssetLoader, GAssetLoader,
    UPackage as UPackageAsset, UTextureAsset, USoundAsset, UMeshAsset,
    FPackageFileSummary, FObjectExport, FObjectImport,
)

from .engine.texture import (
    FColor,
    UPalette,
    FMipmapBase,
    FMipmap,
    ETextureFormat,
    ELODSet,
    UBitmap,
    UTexture,
    FTextureInfo,
    FFontCharacter,
    FFontPage,
    UFont,
)

from .engine.mesh import (
    FMeshVert,
    FMeshUV,
    FMeshFloatUV,
    FMeshTri,
    FMeshWedge,
    FMeshExtWedge,
    FMeshFace,
    FMeshMaterial,
    FMeshVertConnect,
    FMeshAnimSeq,
    UMesh,
    ULodMesh,
)

from .audio import (
    USound, UAudioSubsystem,
    Voice, Sample, FPlayingSound,
)

from .graphics import (
    URenderDevice, UOpenGLRenderDevice, UDirect3DRenderDevice,
    FSceneNode, FSpanBuffer,
    UTexture as GTexture,
    UMesh as GMesh,
    UModel,
    UPolys,
)

try:
    from .graphics.opengl import FOpenGLRenderer, VulkanRenderer, create_renderer
except ImportError:
    FOpenGLRenderer = None
    VulkanRenderer = None
    create_renderer = None

from .window import (
    UViewport, UClient, UInput, UConsole,
    EInputKey, EInputAction, EMouseButtons,
    MessageBox, InputBox,
)

from .ucc import (
    UCCMain, UCommandlet,
    FScriptCompiler, UScriptParser,
    UMakeCommandlet,
)

__all__ = [
    "core",
    "engine",
    "audio",
    "graphics",
    "window",
    "ucc",
    "FName",
    "FString",
    "FTime",
    "FVector",
    "FPlane",
    "FRotator",
    "FQuat",
    "FMatrix",
    "TArray",
    "TMap",
    "FGuid",
    "FCompactIndex",
    "UObject",
    "UClass",
    "UStruct",
    "UFunction",
    "UState",
    "UPackage",
    "UPackageMap",
    "FArchive",
    "FArchiveFileReader",
    "FArchiveMemoryReader",
    "FArchiveFileWriter",
    "FOutputDevice",
    "FOutputDeviceNull",
    "FOutputDeviceStdout",
    "FOutputDeviceFile",
    "GNull",
    "GLog",
    "GError",
    "FFileManager",
    "FConfigCacheIni",
    "FMalloc",
    "FMallocAnsi",
    "FObjectExport",
    "FObjectImport",
    "FGenerationInfo",
    "FPackageFileSummary",
    "ULinker",
    "ULinkerLoad",
    "ULinkerSave",
    "FLazyLoader",
    "load_package",
    "AActor",
    "APawn",
    "APlayerPawn",
    "AWeapon",
    "AInventory",
    "AAmmo",
    "APickup",
    "ABrush",
    "AZoneInfo",
    "ALevelInfo",
    "AProjectile",
    "ACamera",
    "AController",
    "APlayerController",
    "AGameInfo",
    "ULevel",
    "UGameEngine",
    "FCoords",
    "FActorLink",
    "EPhysics",
    "UURL",
    "UNetDriver",
    "UNetConnection",
    "UChannel",
    "UControlChannel",
    "UActorChannel",
    "UFileChannel",
    "UPendingLevel",
    "UNetPendingLevel",
    "EConnectionState",
    "EChannelType",
    "AssetLoader",
    "GAssetLoader",
    "UPackageAsset",
    "UTextureAsset",
    "USoundAsset",
    "UMeshAsset",
    "FColor",
    "UPalette",
    "FMipmapBase",
    "FMipmap",
    "ETextureFormat",
    "ELODSet",
    "UBitmap",
    "UTexture",
    "FTextureInfo",
    "FFontCharacter",
    "FFontPage",
    "UFont",
    "FMeshVert",
    "FMeshUV",
    "FMeshFloatUV",
    "FMeshTri",
    "FMeshWedge",
    "FMeshExtWedge",
    "FMeshFace",
    "FMeshMaterial",
    "FMeshVertConnect",
    "FMeshAnimSeq",
    "UMesh",
    "ULodMesh",
    "USound",
    "UAudioSubsystem",
    "Voice",
    "Sample",
    "FPlayingSound",
    "URenderDevice",
    "UOpenGLRenderDevice",
    "UDirect3DRenderDevice",
    "FSceneNode",
    "FSpanBuffer",
    "UModel",
    "UPolys",
    "FOpenGLRenderer",
    "VulkanRenderer",
    "create_renderer",
    "UViewport",
    "UClient",
    "UInput",
    "UConsole",
    "EInputKey",
    "EInputAction",
    "EMouseButtons",
    "MessageBox",
    "InputBox",
    "UCCMain",
    "UCommandlet",
    "FScriptCompiler",
    "UScriptParser",
    "UMakeCommandlet",
]